kafka:
  servers: "localhost:9092"
  securityProtocol: "SSL"
  ssl:
    truststoreLocation: "/credentials/client.truststore.jks"
    truststorePassword: ""
    keystoreType: "PKCS12"
    keystoreLocation: "/credentials/client.keystore.p12"
    keystorePassword: ""
    keyPassword: ""